generate_data/app/main/models.py
from peewee import CharField

from app.base_model import BaseModel


class User(BaseModel):
    name = CharField(max_length=100)
    email = CharField(max_length=150, unique=True, index=True)
    phone = CharField(max_length=100, null=True)

generate_data/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, SubmitField, HiddenField
from wtforms.validators import DataRequired, Length


class GenerateDataForm(FlaskForm):
    submit = SubmitField('Generate')


class NameForm(FlaskForm):
    id = HiddenField('id')
    name = StringField(
        'What is your name?',
        validators=[DataRequired(), Length(3, 100)],
        render_kw={'placeholder': 'Full name'}
    )
    email = EmailField(
        'What is your email?',
        validators=[DataRequired(), Length(10, 150)],
        render_kw={'placeholder': 'Email'}
    )
    submit = SubmitField('Add')

generate_data/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import routes

generate_data/app/main/routes.py
from flask import render_template, redirect, url_for, flash, request
from datetime import datetime
from flask_paginate import Pagination, get_page_parameter

from app.main import main
from app.main.forms import NameForm, GenerateDataForm
from app.main.models import User
from generate_data.main import main as generate_data
from generate_data.data import emails_data
from app.main.utils import parse_range_from_paginator


@main.route('/', methods=['POST', 'GET'])
def index():
    """Home page"""
    form = GenerateDataForm()

    if form.validate_on_submit():
        if not User.select():
            emails = generate_data(emails_data)
            for name, email in emails:
                user = User(name=name, email=email)
                user.save()
            flash('Database filled with test data')
        else:
            flash('Database is not empty')

    return render_template(
        'index.html',
        title='Home page',
        current_time=datetime.utcnow(),
        form=form
    )


@main.route('/email', methods=['POST', 'GET'])
def add_email():
    """Add name and email form page"""
    form = NameForm()

    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        message = f'User with name {name} already registered'
        if not User.select().where(User.email == email):
            user = User(name=name, email=email)
            user.save()
            message = f'User with name {name} just registered'

        flash(message)
        return redirect(url_for('main.add_email'))

    return render_template(
        'main/email.html',
        title='Register user',
        form=form
    )


@main.route('/email/show')
def show_emails():
    """Show user information"""
    search = False
    q = request.args.get('q')
    if q:
        search = True

    page = request.args.get(get_page_parameter(), type=int, default=1)

    users = User.select()
    pagination = Pagination(page=page, total=users.count(), search=search, record_name='users')
    start, stop = parse_range_from_paginator(pagination.info)
    return render_template(
        'main/show_emails.html',
        title='Show users',
        users=users[start:stop],
        pagination=pagination,
    )


@main.route('/email/edit/<int:user_id>')
def edit_email(user_id):
    """Edit user"""
    user = User.select().where(User.id == user_id).first()
    form = NameForm()
    if not user:
        flash(f'User with id: {user_id} not found. You can add user in this form.')
        return redirect(url_for('main.add_email'))

    form.id.data = user.id
    form.id.label.text = ''
    form.name.label.text = 'Edit this name'
    form.email.label.text = 'Edit this email'

    form.name.data = user.name
    form.email.data = user.email
    form.submit.label.text = 'Edit'

    return render_template(
        'main/edit_email.html',
        title=f'Edit user {user.name}',
        form=form
    )


@main.route('/email/update', methods=['POST'])
def update_email():
    """Update user from form"""
    form = NameForm()
    if form.validate_on_submit():
        user_id = form.id.data
        user_name = form.name.data
        user_email = form.email.data

        user = User.select().where(User.id == user_id).first()
        user.name = user_name
        user.email = user_email
        try:
            user.save()
            flash(f'{user_name} updated')
        except Exception:
            flash(f'Email already added into database')

    return redirect(url_for('main.index'))


@main.route('/email/delete', methods=['POST'])
def delete_emails():
    """Delete selected users"""
    if request.method == 'POST':
        message = 'Deleted: '
        selectors = list(map(int, request.form.getlist('selectors')))

        if not selectors:
            flash('Nothing to delete')
            return redirect(url_for('main.show_emails'))

        for selector in selectors:
            user = User.get(User.id == selector)
            message += f'{user.email} '
            user.delete_instance()

        flash(message)
        return redirect(url_for('main.show_emails'))

generate_data/app/templates/main/add_email.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
    <div class="page-header">
        <h1>Register user</h1>
    </div>
    {% include 'messages.html' %}
    <form action="{{ url_for('main.add_email') }}" method="POST">
        {{ form.csrf_token }}
        {{ wtf.form_field(form.name) }}
        {{ wtf.form_field(form.email) }}
        {{ wtf.form_field(form.submit) }}
    </form>
{% endblock page_content %}

generate_data/app/templates/main/edit_email.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>
    {% include 'messages.html' %}
    <div class="col-md-4">
        <form action="{{ url_for('main.update_email') }}" method="POST">
            {{ form.csrf_token }}
            {{ wtf.form_field(form.id) }}
            {{ wtf.form_field(form.name) }}
            {{ wtf.form_field(form.email) }}
            {{ wtf.form_field(form.submit) }}
        </form>
    </div>
{% endblock page_content %}

generate_data/app/templates/main/email.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
<div class="page-header">
    <h1>Register user</h1>
</div>
{% include 'messages.html' %}

<form action="{{ url_for('main.add_email') }}" method="POST">
    {{ form.csrf_token }}
    {{ wtf.form_field(form.name) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.submit) }}
</form>
{% endblock page_content %}

generate_data/app/templates/main/show_emails.html
{% extends '_base.html' %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
<div class="page-header">
    <h1>Register user</h1>
</div>
{% include 'messages.html' %}

<button type="button" class="btn btn-primary" id="selectButton" onclick="toggle()">Select all</button>
<button type="submit" class="btn btn-danger" form="userForm">Delete</button>
<hr>
{{ pagination.info }}
{{ pagination.links }}

<form action="{{ url_for('main.delete_emails') }}" method="post" id="userForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="table-responsive">
        <table class="table table-hover table-striped" id="userTable">
            <thead>
            <tr>
                <th scope="col">Select</th>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Edit</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
            <tr>
                <td>
                    <input type="checkbox" name="selectors" class="checkbox" value="{{ user.id }}"/>
                </td>
                <td>{{ loop.index + pagination.skip }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <a href="{{ url_for('main.edit_email', user_id=user.id) }}">
                        <button type="button" class="btn btn-info">Edit</button>
                    </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</form>
<hr>
{{ pagination.info }}
{{ pagination.links }}
{% endblock page_content%}