generate_data/app/weather/models.py
from peewee import CharField, ForeignKeyField

from app.base_model import BaseModel


class Country(BaseModel):
    code = CharField(max_length=2, unique=True, index=True)
    name = CharField(max_length=100, unique=True, index=True)


class City(BaseModel):
    name = CharField(max_length=100, unique=True, index=True)
    country = ForeignKeyField(Country, backref='city')

generate_data/app/weather/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class CityForm(FlaskForm):
    city_name = StringField(
        'What city weather are you interested in?',
        validators=[DataRequired(), Length(3, 100)],
        render_kw={'placeholder': 'Full name'}
    )
    submit = SubmitField('Show')

generate_data/app/weather/__init__.py
from flask import Blueprint

weather = Blueprint('weather', __name__, url_prefix='/weather')

from app.weather import routes

generate_data/app/weather/routes.py
from flask import (
    abort,
    render_template,
    redirect,
    request,
    url_for,
    flash,
    current_app
)

from app.weather import weather
from app.weather.forms import CityForm
from weather.getting_weather import main as getting_weather
from app.weather.models import Country, City


@weather.route('/', methods=['GET', 'POST'])
def index():
    """Weather page"""
    form = CityForm()
    city_weather = None
    country = None
    city_name = None

    if form.validate_on_submit():
        api_key = current_app.config['WEATHER_API_KEY']
        city_name = form.city_name.data
        city_weather = getting_weather(city_name, api_key)
        if 'error' in city_weather:
            flash(city_weather['error'])
            return redirect(url_for('weather.index'))
        country = Country.select().where(Country.code == city_weather['country']).first()
        city_weather['country'] = country.name

    return render_template(
        'weather/get_weather.html',
        title='Get city weather',
        form=form,
        city_name=city_name,
        country=country,
        city_weather=city_weather
    )


@weather.route('/show/city')
def show_city():
    """Show cities added into database"""
    cities = City.select()

    country_name = request.args.get('country_name')
    if country_name:
        country = Country.select().where(Country.name == country_name).first()
        if country:
            cities = country.city

    return render_template(
        'weather/show_cities_weather.html',
        title='Show cities weather',
        cities=cities
    )


@weather.route('/show/city/<string:city_name>')
def show_city_detail(city_name):
    """Show detail about city added into database"""
    api_key = current_app.config['WEATHER_API_KEY']
    city_name = city_name.capitalize()

    city = City.select().where(City.name == city_name).first()
    if not city:
        abort(404)

    city_weather = getting_weather(city.name, api_key)
    if 'error' in city_weather:
        flash(city_weather['error'])
        return redirect(url_for('weather.index'))

    city_weather['country'] = city.country.name
    city_weather['name'] = city.name

    return render_template(
        'weather/show_city_detail_weather.html',
        title='Show cities weather',
        city=city_weather
    )


@weather.route('/add/city', methods=['POST'])
def add_city():
    """Add city to monitoring"""
    if request.method == 'POST':
        city = request.form.get('city').capitalize()
        country = request.form.get('country')
        city_check = City.select().where(City.name == city).first()
        if city_check:
            flash(f'{city} already in database')
            return redirect(url_for('weather.index'))

        city_instance = City(
            name=city,
            country=country
        )
        city_instance.save()

        flash(f'City: {city} added to db')

    return redirect(url_for('weather.index'))

generate_data/app/templates/weather/get_weather.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
<div class="page-header">
    <h1>Show weather info</h1>
</div>
{% include 'messages.html' %}

<form action="{{ url_for('weather.index') }}" method="POST">
    {{ form.csrf_token }}
    {{ wtf.form_field(form.city_name) }}
    {{ wtf.form_field(form.submit) }}
</form>

{% if city_weather %}
<div class="col-md-4 table-responsive">
    <h3>Weather info about city {{ city_name.capitalize() }}, {{ country.name }}</h3>
    <table class="table table-hover table-striped" id="userTable">
        <thead>
            <tr>
                <th scope="col">Field</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
        {% for field, value in city_weather.items() %}
            <tr>
                <td>{{ field.capitalize() }}</td>
                {% if field == 'icon_url' %}
                <td class="bg-info"><img src="{{ value }}" alt=""></td>
                {% else %}
                <td>{{ value }}</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <form action="{{ url_for('weather.add_city') }}" method="post" id="userForm">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="hidden" name="city" value="{{ city_name }}"/>
        <input type="hidden" name="country" value="{{ country.id }}"/>
        <button type="submit" class="btn btn-primary">Add city</button>
    </form>
</div>
{% endif %}

{% endblock page_content %}

generate_data/app/templates/weather/show_cities_weather.html
{% extends '_base.html' %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
<div class="page-header">
    <h1>Show cities in database</h1>
</div>
{% include 'messages.html' %}

<button type="button" class="btn btn-primary" id="selectButton" onclick="toggle()">Select all</button>
<button type="submit" class="btn btn-danger" form="userForm">Delete</button>
<hr>

<form action="{{ url_for('main.delete_emails') }}" method="post" id="userForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="col-md-4 table-responsive">
        <table class="table table-hover table-striped" id="userTable">
            <thead>
            <tr>
                <th scope="col">Select</th>
                <th scope="col">#</th>
                <th scope="col">City</th>
                <th scope="col">Country</th>
            </tr>
            </thead>
            <tbody>
            {% for city in cities %}
            <tr>
                <td>
                    <input type="checkbox" name="selectors" class="checkbox" value="{{ city.id }}"/>
                </td>
                <td>{{ loop.index }}</td>
                <td>
                    <a href="{{ url_for('weather.show_city_detail', city_name=city.name) }}">
                        {{ city.name }}
                    </a>
                </td>
                <td>
                    <a href="?country_name={{ city.country.name }}">
                        {{ city.country.name }}
                    </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</form>
<hr>
{% endblock page_content%}

generate_data/app/templates/weather/show_city_detail_weather.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
<div class="page-header">
    <h1>Show weather info</h1>
</div>
{% include 'messages.html' %}

<div class="col-md-4 table-responsive">
    <h3>Weather info about city {{ city.name}}, {{ city.country }}</h3>
    <table class="table table-hover table-striped" id="userTable">
        <thead>
            <tr>
                <th scope="col">Field</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
        {% for field, value in city.items() %}
            <tr>
                <td>{{ field.capitalize() }}</td>
                {% if field == 'icon_url' %}
                <td class="bg-info"><img src="{{ value }}" alt=""></td>
                {% else %}
                <td>{{ value }}</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock page_content %}